### ISSUE TITLE
Supporting camelcase

### ISSUE THREAD

**Issue by aniravi24** [valtyr/prisma-kysely#10]
Thanks for this library! 

Would it be possible to support camelcase, like the [kysely-codegen](https://github.com/RobinBlomberg/kysely-codegen) library?

The final `DB` type that gets generated still has all the keys in snake case, so it would be awesome to be able to configure that as camel case as well.

**Comment by valtyr** [comment]
Let me make sure I understand you correctly. You mean that your Prisma schema generates a database that uses snake case names, but you want to generate types for Kysely that use camel case and depend on the camel case plugin?

If that's the case it should be pretty straightforward to implement. 

I'd be interested to hear what your use case is for this though. Is there something holding you back from renaming the fields in your schema so they use camel case?

**Comment by valtyr** [comment]
Hey I've made a first attempt at addressing this. Could you try using snapshot version `0.0.0-snapshot-20230323111034` and setting `camelCase = true` in the generator config:

```prisma
generator kysely {
    provider  = "prisma-kysely"
    // ...
    camelCase = true
}
```

And of course use the camel case plugin when you instantiate the Kysely instance.

Let me know if this works for you 😄

**Comment by aniravi24** [comment]
> Let me make sure I understand you correctly. You mean that your Prisma schema generates a database that uses snake case names, but you want to generate types for Kysely that use camel case and depend on the camel case plugin?
> 
> If that's the case it should be pretty straightforward to implement.
> 
> I'd be interested to hear what your use case is for this though. Is there something holding you back from renaming the fields in your schema so they use camel case?

Not quite, my Prisma schema does use camel case (underlying DB is using snake case but I map all tables and fields to camel case), and most of the types are also in camel case in the output. The issue is that the final `DB` type export that the library is generating has all the table names in snake case instead of camel case.

**Comment by valtyr** [comment]
Ah gotcha. Try using the snapshot. If I understand you correctly it should solve this issue.

**Comment by aniravi24** [comment]
snapshot works! It outputs in camelcase now.

```typescript
export interface DB {
  taxAuthority: TaxAuthority;
}
```

**Comment by luccasr73** [comment]
this seems like https://github.com/valtyr/prisma-kysely/issues/4, no?
