### ISSUE TITLE
it should support to generate type with @@map() not model name block

### ISSUE THREAD

**Issue by annibuliful** [valtyr/prisma-kysely#2]
<img width="1142" alt="Screenshot 2566-03-16 at 21 52 33" src="https://user-images.githubusercontent.com/5283709/225655866-5511f300-b0a3-43c1-a913-aca392ef3578.png">

<img width="519" alt="Screenshot 2566-03-16 at 21 52 58" src="https://user-images.githubusercontent.com/5283709/225655990-f35354d3-c503-4323-80f0-6837efae6fc4.png">

**Comment by valtyr** [comment]
Nice catch! I'll create a bugfix for this.

**Comment by valtyr** [comment]
Hey @annibuliful

I've published a snapshot with the tag [1.0.6-snapshot-20230316173040](https://www.npmjs.com/package/prisma-kysely/v/1.0.6-snapshot-20230316173040), it would be great if you could test it out and check if it fixes your issue before I merge and release.

Let me know 😄

**Comment by annibuliful** [comment]
It works correctly. Thank you for fixing. I cannot waiting for release this feature 😃 

<img width="458" alt="Screenshot 2566-03-17 at 08 23 47" src="https://user-images.githubusercontent.com/5283709/225788287-a001e91f-97fe-4989-982a-b5aba751e6ac.png">

<img width="379" alt="Screenshot 2566-03-17 at 08 24 10" src="https://user-images.githubusercontent.com/5283709/225788327-9d3881c0-f1b7-4bbf-b26d-527190f971bd.png">

**Comment by valtyr** [comment]
@annibuliful Version `1.0.7` has been released 😄
