### ISSUE TITLE
config to allow enums in separate entrypoint

### ISSUE THREAD

**Issue by juliusmarminge** [valtyr/prisma-kysely#33]
hi - love the new enum stuff <3

one thought - would it be possible to allow a config option to let us generate them into a separate file?

defualt can stay as is - but i would like the option to say i want the runtime stuff in a separate entrypoint than the types :)

**Comment by valtyr** [comment]
Hey @juliusmarminge, great to see you here! I think this is would be a good improvement. I've left a few comments on your PR, otherwise it's looking good. 🤘

Thank you for all the good work on tRPC by the way!
