### ISSUE TITLE
Generating conflict types

### ISSUE THREAD

**Issue by rolanday** [valtyr/prisma-kysely#36]
I am scratching my head on this one because switched project from Next to Remix, using exact same prisma file and `"prisma-kysely": "^1.2.0"` ver. Primsa file is configured to output db.types.ts, and works flawlessly under nextjs project. In remix project, I get two files:

`
types.ts
db.types.ts
`

And type `types.ts` has conflicting symbols like so:

```
export type Audience = "friends" | "private" | "public";
export const Audience = {
  friends: "friends",
  private: "private",
  public: "public",
};
```

Any ideas?

**Comment by rolanday** [comment]
Here is repo link: https://github.com/rolanday/remix-kysely

To see issue, please perform the following steps:

1. clone rolanday/remix-kysely
2. npm install
3. npm run db:gen
4. Note generated files in ./app/server folder

Really odd this happens for me only under remix project (have run same under NextJS and Qwik and output as expected).

**Comment by valtyr** [comment]
I'll take a look at this when I get the chance. Thank you for providing a reproduction.
