### ISSUE TITLE
@map for table fields is incorrect

### ISSUE THREAD

**Issue by annibuliful** [valtyr/prisma-kysely#4]
<img width="900" alt="Screenshot 2566-03-19 at 22 21 54" src="https://user-images.githubusercontent.com/5283709/226186168-c0b5024c-86ca-4ccb-ab8a-3e0f862910f8.png">
When  I set map `action` to `map_action` on database level it's not when generate.

As you see it should me `map_action` not `action`
<img width="361" alt="Screenshot 2566-03-19 at 22 23 44" src="https://user-images.githubusercontent.com/5283709/226186293-74055182-b864-422d-a975-be373b081ac9.png">

**Comment by valtyr** [comment]
Hey there. I spent some time looking into this and it seems like Prisma don't provide information about field mappings to generators. Check out this issue: https://github.com/prisma/prisma/issues/3998. For the time being, I don't think there's any reasonable way to support this. Sorry about that 😞 

In the meantime, you should just be able to call the field `map_action`. I know it's ugly to have a single snake case field... but probably better than not having access to the field at all?

Awesome to have someone like you using the library and reporting issues. It's super valuable, thank you again 😄

**Comment by valtyr** [comment]
I've added a section to the README that explains this

**Comment by janpio** [comment]
Please make sure to leave a comment on https://github.com/prisma/prisma/issues/3998 that mentions that this leads to a limitation in your custom generator - we will take this into account with prioritization. Thanks.

**Comment by luxaritas** [comment]
I was just working on a generator myself, and it looks like this does exist - `DMMF.Field` has a property that gets filled out with `@map` statements called `dbName`. Note that it's incorrect on the typings, which denote it as an array called `dbNames`. I have a [pending PR](https://github.com/prisma/prisma/pull/18694) for that

**Comment by valtyr** [comment]
@luxaritas Awesome, thanks for letting me know. I'll look into this.

**Comment by valtyr** [comment]
I've made a first pass at adding support for this in pr #22. Here's a snapshot version for you guys to try: `0.0.0-snapshot-20230420160205`. @annibuliful

**Comment by annibuliful** [comment]
Thank you so much
