### ISSUE TITLE
kyselyType annotation: support types defined in other modules

### ISSUE THREAD

**Issue by HandyMenny** [valtyr/prisma-kysely#61]
I noticed that kyselyType annotation doesn't work with types defined in other ts files. 
I can fix this by adding something like `import type { Custom } from 'other-module.js'` in the generated file, but it would be much better to have this feature built-in.

**Comment by Wundero** [comment]
As an addendum to this, I have a use case where I want to put `export type Custom = ColumnType<...>;` into the file, and use the custom type as a column type. I think having some form of `prelude` where we can provide custom code which should be inserted into the generated file would be nice.

**Comment by valtyr** [comment]
I think an optional prelude is a good idea. I'll try to get to this soon.

**Comment by alandotcom** [comment]
Workaround for now. We did this to have Json types be equivalent between Prisma and Kysely

```ts
declare global {
  export type JsonObject = { [Key in string]?: JsonValue }

  /**
   * From https://github.com/sindresorhus/type-fest/
   * Matches a JSON array.
   */
  export interface JsonArray extends Array<JsonValue> {}

  /**
   * From https://github.com/sindresorhus/type-fest/
   * Matches any valid JSON value.
   */
  export type JsonValue =
    | string
    | number
    | boolean
    | JsonObject
    | JsonArray
    | null
}
```

Can then be used in schema annotations, as the type is available globally

```
  /// @kyselyType(JsonValue)
```

To keep things clean, also possible to export in a global namespace,

```ts
declare global {
  namespace App {
      ....
  }
}

**Comment by valtyr** [comment]
Turns out this was possible all along, and I didn't realize it. See this comment:
https://github.com/valtyr/prisma-kysely/issues/83#issuecomment-1788758466
