### ISSUE TITLE
SQL Server Support?

### ISSUE THREAD

**Issue by BStoller** [valtyr/prisma-kysely#65]
@valtyr would this library support interpreting Prisma SQL Server Schemas? I am implementing a custom kysely dialect and wanted to check to see if I could use this library

**Comment by dylel** [comment]
I've tried using sql server, for some reason this doesn't seem to be supported. I just get 

```spawn prisma-kysely ENOENT
```
Not sure why this needs to be dialect specific, shouldn't this just look at the types?

**Comment by valtyr** [comment]
Let me know you run into any issues of if I can be of any help @BStoller

**Comment by dylel** [comment]
I've submitted a pr #68  for this change, honestly a little unsure on the type mapping but seems good
