### ISSUE TITLE
Getting Invalid prisma-kysely config error

### ISSUE THREAD

**Issue by MagedMYoussef** [valtyr/prisma-kysely#73]
I'm trying to use pirmsa-kysely with an existing prisma client, but I'm getting some issues.

Here's the error I get when trying to run `prisma migrate dev`:
```
prisma:error Invalid prisma-kysely config
prisma:error databaseProvider: Invalid input
```

And here's my configuration in schema.primsa:
```
generator client {
    provider = "prisma-client-js"
}

generator kysely {
    provider = "prisma-kysely"
}

datasource db {
    provider     = "postgres"
    relationMode = "prisma"
    url          = env("DATABASE_URL")
}
```

Any clue what do I need to change? And also can I run both generators alongside or it won't be possible?
Thanks.

**Comment by valtyr** [comment]
Hey there. You need to change the datasource provider name to `"postgresql"` instead of `"postgres"`. Prisma supports postgres as an alias for postgresql so I think we probably should too, but we don't as of right now.
