### ISSUE TITLE
Feature Request: External typescript types

### ISSUE THREAD

**Issue by fauh45** [valtyr/prisma-kysely#83]
While it is already possible to set typescript type declaration for columns in prisma schema using  `/// @kyselyType( ... )`. I don't think there's a way to set the column type with typescript definition outside of the schema. This will be so useful for JSON column types, as sometimes it does contains a complex metadata structure, that's usually opaque to the programmer. 

I suppose it'll be great to have something like,

**types.ts**
```typescript
export type Metadata = {
    tracking_id: string,
    userLocation: {
        ...
    },
    ...
}
```

**prisma.schema**
```prisma
model User {
    id String @id
    
    // Import would be based on the root of the project, or maybe the output of the file. This part might be the most complex part, resolving the module
    /// @kyselyType( import('./types.ts').Metadata )
   module Json
}
```

**Comment by valtyr** [comment]
Hey there @fauh45, this is a valid point. There's a solution on the roadmap which is tracked in #61. The idea is to allow users to include a "prelude", basically a string prepended to the generated file. This prelude could include import statements etc.

The funny thing is though is that we already support the exact syntax you suggested by total accident! If you make the import relative to the directory the generated file ends up in, it works great. This was absolutely unintentional which is hilarious, but actually a pretty powerful feature.

**Comment by valtyr** [comment]
I might just add this to the README to be fair 😆

**Comment by valtyr** [comment]
The schema:

```prisma
datasource db {
    provider = "mysql"
    url      = "mysql://root:mysql@localhost:22332/test"
}

generator kysely {
    provider = "node ./dist/bin.js"
}

model User {
    id String @id

    /// @kyselyType( import('./jsonTypes.ts').Metadata )
    module Json
}
```

Gives the following result:

<img width="658" alt="CleanShot 2023-11-01 at 10 50 03@2x" src="https://github.com/valtyr/prisma-kysely/assets/3050355/a8fa09d4-80c8-442e-9b82-7ae2133989e2">

With the file `jsonTypes.ts` located in the output directory.

**Comment by valtyr** [comment]
Hey @fauh45 if you still want to create a PR that adds this to the README that would be great :)
Otherwise, I'm closing this issue for now.
